# 问题介绍：生成100个用户，每个用户度均为15的网络拓扑对应的邻接矩阵

In [1]:
import numpy as np
import random

In [2]:
Adjacency_Matrix  = np.zeros(shape=(100,100))#定义100*100维的邻接矩阵
sum_list=[]#共100个数据
connect_number=[]#100个用户被连接的次数

In [3]:
count=0
while sum_list.count(15)!=200:
    count=count+1
    print("第",(count),"次循环")
    sum_list.clear()
    break_flag=False
    Adjacency_Matrix  = np.zeros(shape=(100,100))
    for i in range(0,100):
        if (i==0):
            Adjacency_Matrix[i][i+1]=1
            Adjacency_Matrix[i][99]=1
        elif (i==99):
            Adjacency_Matrix[i][0]=1
            Adjacency_Matrix[i][i-1]=1
        else:
            Adjacency_Matrix[i][i+1]=1
            Adjacency_Matrix[i][i-1]=1
            
    connect_number.clear()#100个用户被连接的次数
    for i in range (0,100):
        connect_number.append(2)
    
    
    #开始为邻接矩阵赋值
    for i in range (0,100):
        random_code=[]
        k=15
        list=[]
        for j in range(0,100):
            if (Adjacency_Matrix[i][j]==1):
                k=k-1
                list.append(j)
        print("第",count,"循环中第",i,"个用户的k值为：",k)
        print("第",count,"循环中第",i,"个用户的list值为：",list)
        
        if (k<=0):
            continue            
        if (k>0):
            number1=0
            number2=0
            for j in range(i+1,100):
                if (connect_number[j]>=15):
                    number1=number1+1
                if (Adjacency_Matrix[i][j]==1):
                    number2=number2+1
                if (connect_number[j]>=15 and Adjacency_Matrix[i][j]==1):
                    number1=number1-1                      
            if (99-i-number1-number2<k):
                break_flag=True
            else:
                e=0
                q=0
                while e!=k or q!=len(list)*k:
                    e=0
                    q=0
                    random_code=[]
                    random_code=random.sample(range(i+1, 100), k)
                    for j in range(0,k):
                        if (connect_number[random_code[j]]<15):
                            e=e+1
                    for p in range(0,len(list)):
                        for j in range(0,k):
                            if (list[p]!=random_code[j]):
                                q=q+1
                for j in range(0,k):
                    Adjacency_Matrix[i][random_code[j]]=1
                    Adjacency_Matrix[random_code[j]][i]=1
                    connect_number[random_code[j]]=connect_number[random_code[j]]+1
                connect_number[i]=15
                print("第",count,"循环中第",i,"个用户的random_code值为：",random_code)
                print("第",count,"循环中第",i,"个用户的connect_number值为：",connect_number)
            if (break_flag==True):
                continue
            
    print("第",count,"次循环的邻接矩阵",Adjacency_Matrix)
    
    print("行和")
    for i in range(0,100):
        sum=0
        for j in range(0,100):
            sum=sum+Adjacency_Matrix[i][j]
        sum_list.append(sum)
        print(sum_list[i])
    print("*********************************")
    print("列和")
    for i in range(0,100):
        sum=0
        for j in range(0,100):
            sum=sum+Adjacency_Matrix[j][i]
        sum_list.append(sum)
        print(sum_list[i])
    print("***********************************************************************")   

第 1 次循环
第 1 循环中第 0 个用户的k值为： 13
第 1 循环中第 0 个用户的list值为： [1, 99]
第 1 循环中第 0 个用户的random_code值为： [95, 51, 74, 31, 68, 88, 13, 46, 39, 9, 64, 62, 36]
第 1 循环中第 0 个用户的connect_number值为： [15, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 3, 2, 2, 2, 3, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2]
第 1 循环中第 1 个用户的k值为： 13
第 1 循环中第 1 个用户的list值为： [0, 2]
第 1 循环中第 1 个用户的random_code值为： [71, 99, 4, 53, 88, 65, 20, 49, 12, 62, 19, 58, 55]
第 1 循环中第 1 个用户的connect_number值为： [15, 15, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 3, 2, 3, 2, 3, 2, 2, 3, 2, 2, 2, 4, 2, 3, 3, 2, 2, 3, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 3]
第 1 循环中第 2 个用户的k值为： 13
第 1 循环中第 2 个用户的list值为： [1, 

15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
10.0
15.0
15.0
15.0
11.0
14.0
13.0
15.0
15.0
15.0
15.0
15.0
15.0
*********************************
列和
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
10.0
15.0
15.0
15.0
11.0
14.0
13.0
15.0
15.0
15.0
15.0
15.0
15.0
***********************************************************************
第 2 次循

第 2 循环中第 51 个用户的random_code值为： [80, 72]
第 2 循环中第 51 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 8, 3, 7, 12, 9, 11, 7, 15, 7, 8, 12, 9, 9, 8, 11, 10, 9, 5, 10, 5, 11, 8, 6, 7, 10, 3, 11, 8, 10, 9, 5, 11, 6, 10, 11, 11, 8, 10, 7, 8, 10, 9, 5, 7, 12, 11, 10, 9]
第 2 循环中第 52 个用户的k值为： 7
第 2 循环中第 52 个用户的list值为： [0, 5, 8, 20, 34, 45, 51, 53]
第 2 循环中第 52 个用户的random_code值为： [81, 98, 77, 58, 71, 88, 89]
第 2 循环中第 52 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 3, 7, 12, 9, 11, 8, 15, 7, 8, 12, 9, 9, 8, 11, 10, 9, 5, 10, 6, 11, 8, 6, 7, 10, 4, 11, 8, 10, 10, 5, 11, 6, 10, 11, 11, 9, 11, 7, 8, 10, 9, 5, 7, 12, 11, 11, 9]
第 2 循环中

第 3 循环中第 9 个用户的random_code值为： [84, 48, 45, 54, 38, 39, 24, 28, 19, 23, 44, 20]
第 3 循环中第 9 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 2, 3, 6, 3, 5, 3, 3, 4, 4, 6, 4, 2, 3, 5, 3, 4, 3, 4, 4, 2, 2, 2, 3, 3, 4, 2, 4, 2, 4, 3, 5, 2, 3, 2, 6, 3, 2, 3, 3, 4, 3, 4, 3, 3, 5, 2, 3, 2, 2, 4, 4, 5, 2, 4, 2, 2, 3, 4, 3, 2, 5, 5, 4, 4, 3, 2, 4, 3, 5, 5, 3, 2, 3, 4, 4, 2, 2, 3, 3, 4, 3, 4, 4, 3, 2, 3, 2, 4, 3, 3]
第 3 循环中第 10 个用户的k值为： 13
第 3 循环中第 10 个用户的list值为： [9, 11]
第 3 循环中第 10 个用户的random_code值为： [62, 41, 27, 39, 22, 80, 71, 87, 57, 34, 51, 52, 90]
第 3 循环中第 10 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 3, 6, 3, 5, 3, 3, 4, 4, 6, 4, 2, 4, 5, 3, 4, 3, 5, 4, 2, 2, 2, 3, 3, 5, 2, 4, 2, 4, 4, 5, 3, 3, 2, 6, 3, 2, 3, 3, 4, 3, 5, 4, 3, 5, 2, 3, 3, 2, 4, 4, 5, 3, 4, 2, 2, 3, 4, 3, 2, 5, 6, 4, 4, 3, 2, 4, 3, 5, 5, 4, 2, 3, 4, 4, 2, 2, 4, 3, 4, 4, 4, 4, 3, 2, 3, 2, 4, 3, 3]
第 3 循环中第 11 个用户的k值为： 12
第 3 循环中第 11 个用户的list值为： [7, 10, 12]
第 3 循环中第 11 个用户的random_code值为： 

第 3 循环中第 80 个用户的k值为： 0
第 3 循环中第 80 个用户的list值为： [7, 10, 19, 27, 28, 32, 33, 35, 46, 57, 58, 67, 74, 79, 81]
第 3 循环中第 81 个用户的k值为： 8
第 3 循环中第 81 个用户的list值为： [26, 48, 58, 59, 74, 80, 82]
第 3 循环中第 81 个用户的random_code值为： [91, 88, 96, 94, 87, 93, 99, 98]
第 3 循环中第 81 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 9, 15, 15, 9, 15, 15, 15, 15, 10, 12, 13, 9, 10, 11, 11, 10, 13]
第 3 循环中第 82 个用户的k值为： 0
第 3 循环中第 82 个用户的list值为： [2, 11, 13, 21, 22, 27, 33, 34, 41, 47, 50, 52, 56, 81, 83]
第 3 循环中第 83 个用户的k值为： 6
第 3 循环中第 83 个用户的list值为： [2, 3, 20, 31, 47, 65, 77, 82, 84]
第 3 循环中第 83 个用户的random_code值为： [93, 97, 91, 99, 95, 96]
第 3 循环中第 83 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 1

第 4 循环中第 45 个用户的k值为： 10
第 4 循环中第 45 个用户的list值为： [2, 15, 23, 44, 46]
第 4 循环中第 45 个用户的random_code值为： [73, 50, 74, 99, 57, 77, 80, 61, 65, 96]
第 4 循环中第 45 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 7, 7, 6, 10, 8, 6, 9, 8, 8, 10, 6, 9, 9, 11, 12, 8, 8, 9, 6, 7, 3, 6, 7, 9, 11, 7, 7, 8, 8, 10, 11, 9, 14, 9, 8, 12, 4, 11, 6, 10, 6, 5, 8, 7, 7, 8, 6, 8, 10, 7, 8, 8, 12, 12]
第 4 循环中第 46 个用户的k值为： 8
第 4 循环中第 46 个用户的list值为： [7, 20, 21, 30, 43, 45, 47]
第 4 循环中第 46 个用户的random_code值为： [80, 70, 95, 62, 79, 49, 81, 54]
第 4 循环中第 46 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 7, 6, 11, 8, 6, 9, 8, 9, 10, 6, 9, 9, 11, 12, 8, 9, 9, 6, 7, 3, 6, 7, 9, 12, 7, 7, 8, 8, 10, 11, 9, 14,

第 5 循环中第 11 个用户的k值为： 10
第 5 循环中第 11 个用户的list值为： [1, 4, 5, 10, 12]
第 5 循环中第 11 个用户的random_code值为： [73, 85, 61, 53, 20, 25, 89, 83, 39, 21]
第 5 循环中第 11 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 2, 4, 2, 2, 3, 2, 4, 4, 5, 7, 4, 4, 3, 3, 2, 3, 3, 2, 3, 3, 3, 7, 4, 5, 2, 5, 2, 4, 4, 4, 4, 4, 4, 6, 4, 7, 2, 4, 2, 4, 3, 3, 3, 3, 5, 2, 5, 2, 3, 7, 4, 3, 2, 3, 3, 3, 6, 5, 2, 3, 6, 4, 3, 3, 3, 3, 3, 3, 2, 3, 3, 3, 5, 4, 4, 2, 3, 3, 4, 2, 4, 2, 2, 3, 2, 5, 3, 3]
第 5 循环中第 12 个用户的k值为： 13
第 5 循环中第 12 个用户的list值为： [11, 13]
第 5 循环中第 12 个用户的random_code值为： [43, 84, 26, 77, 95, 23, 72, 18, 70, 39, 44, 33, 35]
第 5 循环中第 12 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 4, 2, 2, 3, 2, 5, 4, 5, 7, 4, 5, 3, 3, 3, 3, 3, 2, 3, 3, 3, 8, 4, 6, 2, 5, 2, 5, 4, 4, 4, 5, 5, 6, 4, 7, 2, 4, 2, 4, 3, 3, 3, 3, 5, 2, 5, 2, 3, 7, 4, 3, 2, 3, 3, 3, 6, 5, 3, 3, 7, 4, 3, 3, 3, 4, 3, 3, 2, 3, 3, 3, 6, 4, 4, 2, 3, 3, 4, 2, 4, 2, 2, 4, 2, 5, 3, 3]
第 5 循环中第 13 个用户的k值为： 11
第 

第 5 循环中第 80 个用户的k值为： 0
第 5 循环中第 80 个用户的list值为： [17, 19, 21, 33, 37, 60, 61, 64, 66, 70, 74, 76, 78, 79, 81]
第 5 循环中第 81 个用户的k值为： 3
第 5 循环中第 81 个用户的list值为： [6, 14, 19, 27, 31, 36, 41, 50, 66, 74, 80, 82]
第 5 循环中第 81 个用户的random_code值为： [94, 93, 91]
第 5 循环中第 81 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 11, 12, 15, 11, 15, 15, 15, 15, 15, 15, 15, 14, 12, 14, 11, 15, 14, 14]
第 5 循环中第 82 个用户的k值为： 4
第 5 循环中第 82 个用户的list值为： [9, 16, 37, 51, 53, 61, 63, 77, 78, 81, 83]
第 5 循环中第 82 个用户的random_code值为： [95, 99, 96, 93]
第 5 循环中第 82 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 

第 6 循环中第 50 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 7, 10, 10, 9, 8, 6, 7, 13, 12, 13, 6, 9, 7, 13, 9, 11, 10, 7, 7, 12, 6, 8, 14, 7, 4, 9, 4, 7, 8, 6, 9, 6, 9, 8, 7, 8, 9, 8, 7, 10, 5, 8, 8, 14, 8, 9, 11, 7, 13]
第 6 循环中第 51 个用户的k值为： 8
第 6 循环中第 51 个用户的list值为： [12, 21, 24, 28, 33, 50, 52]
第 6 循环中第 51 个用户的random_code值为： [96, 74, 80, 92, 78, 75, 71, 81]
第 6 循环中第 51 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 10, 10, 9, 8, 6, 7, 13, 12, 13, 6, 9, 7, 13, 9, 11, 10, 7, 7, 12, 7, 8, 14, 8, 5, 9, 4, 8, 8, 7, 10, 6, 9, 8, 7, 8, 9, 8, 7, 10, 5, 9, 8, 14, 8, 10, 11, 7, 13]
第 6 循环中第 52 个用户的k值为： 5
第 6 循环中第 52 个用户的list值为： [1, 6, 14,

第 7 循环中第 19 个用户的list值为： [2, 10, 13, 14, 18, 20]
第 7 循环中第 19 个用户的random_code值为： [90, 54, 71, 83, 92, 37, 58, 87, 43]
第 7 循环中第 19 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 5, 3, 4, 4, 6, 2, 7, 6, 3, 5, 5, 3, 6, 6, 5, 4, 5, 5, 4, 5, 5, 4, 6, 5, 6, 3, 3, 4, 4, 4, 6, 7, 4, 3, 3, 5, 4, 5, 4, 4, 3, 6, 8, 5, 7, 6, 4, 4, 5, 5, 5, 5, 4, 5, 4, 4, 3, 4, 2, 3, 7, 7, 5, 3, 4, 5, 6, 9, 4, 5, 3, 5, 2, 7, 4, 4, 5, 4, 4]
第 7 循环中第 20 个用户的k值为： 10
第 7 循环中第 20 个用户的list值为： [3, 12, 16, 19, 21]
第 7 循环中第 20 个用户的random_code值为： [42, 55, 97, 38, 64, 74, 83, 72, 49, 96]
第 7 循环中第 20 个用户的connect_number值为： [15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 5, 3, 4, 4, 6, 2, 7, 6, 3, 5, 5, 3, 6, 6, 5, 4, 5, 6, 4, 5, 5, 5, 6, 5, 6, 3, 3, 4, 5, 4, 6, 7, 4, 3, 4, 5, 4, 5, 4, 4, 3, 6, 8, 6, 7, 6, 4, 4, 5, 5, 5, 6, 4, 6, 4, 4, 3, 4, 2, 3, 7, 7, 6, 3, 4, 5, 6, 9, 4, 5, 3, 5, 2, 7, 4, 5, 6, 4, 4]
第 7 循环中第 21 个用户的k值为： 10
第 7 循环中第 

第 7 循环中第 96 个用户的k值为： 0
第 7 循环中第 96 个用户的list值为： [1, 16, 20, 26, 37, 38, 41, 45, 51, 68, 77, 84, 89, 95, 97]
第 7 循环中第 97 个用户的k值为： 0
第 7 循环中第 97 个用户的list值为： [10, 11, 15, 20, 21, 33, 39, 42, 43, 46, 51, 55, 66, 96, 98]
第 7 循环中第 98 个用户的k值为： 0
第 7 循环中第 98 个用户的list值为： [3, 4, 32, 36, 45, 48, 56, 76, 84, 87, 90, 91, 94, 97, 99]
第 7 循环中第 99 个用户的k值为： 0
第 7 循环中第 99 个用户的list值为： [0, 3, 11, 21, 53, 60, 61, 77, 78, 79, 80, 83, 89, 90, 98]
第 7 次循环的邻接矩阵 [[0. 1. 0. ... 0. 0. 1.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 1.]
 [1. 0. 0. ... 0. 1. 0.]]
行和
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
15.0
1

In [4]:
Adjacency_Matrix

array([[0., 1., 0., ..., 0., 0., 1.],
       [1., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [5]:
np.savetxt('100_Network_Topology_Adjacency_Matrix_Degree_15.txt',Adjacency_Matrix,fmt='%0.8f')#数据存储

In [6]:
Double_Random_Adjacency_Matrix=Adjacency_Matrix

In [7]:
#将邻接矩阵转化成双随机的邻接矩阵
for i in range(0,100):
    for j in range(0,100):
        if (Double_Random_Adjacency_Matrix[i][j]==1):
            Double_Random_Adjacency_Matrix[i][j]=1/15  

In [8]:
np.savetxt('100_Network_Topology_Double_Random_Adjacency_Matrix_Degree_15.txt',Double_Random_Adjacency_Matrix,fmt='%0.8f')#数据存储

In [9]:
Double_Random_Adjacency_Matrix

array([[0.        , 0.06666667, 0.        , ..., 0.        , 0.        ,
        0.06666667],
       [0.06666667, 0.        , 0.06666667, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.06666667, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.06666667,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.06666667, 0.        ,
        0.06666667],
       [0.06666667, 0.        , 0.        , ..., 0.        , 0.06666667,
        0.        ]])